on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      name:
        required: true
        type: string
      tag:
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    name: DigitalOcean Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DO Container Registry
        run: echo "${{ secrets.DO_PAT }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      - name: Build and Push Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.digitalocean.com/${{ inputs.registry }}/${{ inputs.name }}:${{ inputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
