on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  dotnet-version:
    name: Dotnet Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update AppVersion.cs
        run: |
          sed -i 's|public const string Version = ".*";|public const string Version = "${{ inputs.version }}";|' src/OpenSearchService.Domain/Configuration/AppVersion.cs
          cat src/OpenSearchService.Domain/Configuration/AppVersion.cs

      - name: Commit and push updated AppVersion.cs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/OpenSearchService.Domain/Configuration/AppVersion.cs
          git commit -m "ci: update app version to ${{ inputs.version }} [skip ci]" || echo "No changes to commit"
          git push
