on: workflow_call
permissions:
  contents: write

jobs:
  git-version:
    name: Git Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          minor-identifier: /^feat/

      - name: Print the version
        run: |
          echo ${{ steps.version.outputs.version }}
