on:
  workflow_call:
    inputs:
      baseBranch:
        description: "The base branch to compare against. Example: 'main'"
        default: main
        type: string
    outputs:
      version:
        description: "Generated semantic version"
        value: ${{ jobs.git-version.outputs.version }}

permissions:
  contents: write

jobs:
  git-version:
    name: Git Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          minor-identifier: /^feat/
          release-branch: ${{ inputs.baseBranch }}

      - name: Print the version
        run: |
          echo ${{ steps.version.outputs.version }}
